### ISSUE TITLE
Theme depends on SDK

### ISSUE THREAD

**Issue by alexlarsson** [flathub/org.gtk.Gtk3theme.Mint-Y#1]
Using ` "runtime": "org.gnome.Sdk" ` means that the plugin will depend on the sdk, and auto-download that, as reported here:
 https://lists.freedesktop.org/archives/flatpak/2019-July/001641.html

More correct would be to do something like:
```json
  "runtime": "org.freedesktop.Platform",
  "sdk": "org.freedesktop.Sdk",
  "runtime-version": "18.08",
```

**Comment by cstamas** [comment]
This causes strange issue on LM 19.2, see here
https://forums.linuxmint.com/viewtopic.php?f=47&t=302122

**Comment by clefebvre** [comment]
@alexlarsson thanks this is fixed now.

@cstamas I'm not sure this is related to this issue. Some projects recently updated their deps to 19.08 and that's what's causing the issue: 

Warning: Failed to install org.freedesktop.Platform.openh264/x86_64/19.08: runtime/org.freedesktop.Platform.openh264/x86_64/19.08 needs a later flatpak version (1.4.2)

Basically this breaks compatibility in Ubuntu LTS and Linux Mint where flatpak is version 1.0.8.

@alexlarsson Is the dependency bump on openh264/x86_64/19.08 towards flatpak 1.4.2 required? Is there anything that can be done upstream?

Let us know. Failing that, we'll upgrade Flatpak to 1.4.3.

@mtwebster This highlights a little problem within mintinstall. Say you install Blender or Zoom via mintinstall right now, it will fail and abort due to the runtime/org.freedesktop.Platform.openh264/x86_64/19.08 dependency on flatpak 1.4.2+. If you do that from the command line instead (flatpak install flathub us.zoom.Zoom), the installation failure for openh264 is only treated as a warning and doesn't stop Zoom from getting installed.

**Comment by TingPing** [comment]
> Is the dependency bump on openh264/x86_64/19.08 towards flatpak 1.4.2 required?

The feature is actually required and there is no way around it. (For details for openh264 to be legally used it must be a binary shipped by cisco not by us and `flatpak` didn't allow that for extensions in earlier versions)

It was backported to 1.2.x but even if it was backported to 1.0.x there is no reason to believe Ubuntu will ever update it.

Also its worth mentioning that is not a fatal issue. Applications will generally work totally fine except for a few that need h264 and don't bundle codecs.

**Comment by clefebvre** [comment]
Ah thanks @TingPing 

We'll improve mintinstall and backport Flatpak if Ubuntu doesn't react.

I'm not  sure what it's worth but I bumped into this on Launchpad this morning while looking for an Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/flatpak/+bug/1844666.

**Comment by TingPing** [comment]
Yeah @ahayzen was involved with trying to get updates but I don't think it worked out in the end. I think realistically Mint will just have to do it if it wants a good experience.

Anyway I'll close this since this issue is solved.

**Comment by ahayzen** [comment]
@TingPing the flatpak releases 1.0.9 and 1.2.5 were announced on Thursday, it would be impossible for them to have reached users in the Ubuntu archive as SRUs by now (Saturday). So saying "I don't think it worked out in the end" is completely false.

To do a stable release update, I need to prepare a diff on my machine test it myself on a VM for the relevant Ubuntu release, then find a sponsor to upload the diff, then get the SRU team to review the diff and accept it into the proposed archive, then wait for autopkgtests to pass, then manually test the package in the proposed archive against the manual test plan and mark it as passed in the bug, then wait for the package to be in proposed for a least 7 days, and then finally wait for a member of the SRU team to accept the validated package into the archive (but updates aren't accepted on Fridays in case they are bad and need to be reverted/fixed).  Usually this process takes a few weeks :-P

I plan to make the diffs and find a sponsor for them over the coming days/week, I would hope that the updates, if accepted, make it to Ubuntu 18.04 and Ubuntu 19.04 in a few weeks (at which point Mint would pick them up).

@clefebvre If it interests you please subscribe to that bug, as I go through each of these stages I will update the status of the bug.

**Comment by TingPing** [comment]
I didn't realize Ubuntu was getting flatpak updates at all, my mistake.

**Comment by clefebvre** [comment]
@ahayzen thanks! :)
